### ISSUE TITLE
Add support for module imports

### ISSUE THREAD

**Issue by just95** [FreeProving/haskell-src-transformations#11]
## Description

Support for simple `import` declarations should be implemented.

## Motivation

Consider the following two modules.

```haskell
module A where

data Foo = Bar | Baz
```

```haskell
module B where

import A

barToBaz :: Foo -> Foo
barToBaz Bar = Baz
```

Since module imports are currently not supported, `import A` is ignored in `B`. Therefore, the pattern matching compiler does not know which data type `Bar` belongs to and throws an error. This is problematic since the Free Compiler (which uses `haskell-src-transformations` in an optional phase) supports `import` declarations. Users currently have to decide between module imports and pattern matching compilation. The goal is to add support for simple imports such as `import A` to this library.

## Tasks

 - [x] Add a module interface data type, that contains all information that must be preserved per module (for now, this is probably just a map from data type names to constructors).
 - [x] Add a field to `PMState` for available module interfaces (similar to [`envAvailableModules`](https://github.com/FreeProving/free-compiler/blob/master/src/lib/FreeC/Environment.hs#L66) from the Free Compiler's `Environment`).
 - [x] Lookup module interface when an `import` is found and restore the contained information.
 - [x] Report an error when the module interface is not found or the `import` declaration is not supported at the moment (i.e., imports with `qualified`, `hiding`, `as` etc.).
 - [x] Adapt the command line interface such that multiple modules can be processed at once (in topological order).
 - [x] Implement test cases and document the new feature.

## Alternatives

Module imports are processed by the Free Compiler already. Instead of implementing module imports in this library, the [intialization of `PMState`](https://github.com/FreeProving/free-compiler/blob/2ab29e5e516ce0a92ce07644366dc089d8219fc5/src/lib/FreeC/Frontend/Haskell/PatternMatching.hs#L34) could be altered in the Free Compiler. However, that would require us to split the conversion from Haskell modules to the Free Compiler's  intermediate representation (IR) into two phases. In the first phase only imports would be converted to IR. This information can then be used to initialize `PMState` with imported constructors. In a second phase the remaining declarations are transformed using the pattern matching compiler and the resulting declarations are converted to IR. However, adding module imports to the pattern matching compiler as described in the task list above, should be much easier.
