### ISSUE TITLE
Add more development tools

### ISSUE THREAD

**Issue by just95** [FreeProving/haskell-src-transformations#14]
## Description

We should add a `./tool/run.sh` script to run the pattern matching compiler more easily (e.g. with `-Wwarn`) during development and pull updates to existing tools from the Free Compiler repository.

## Motivation

In the Free Compiler we have [a script for running the compiler](https://github.com/FreeProving/free-compiler/blob/master/tool/run.sh) during development without installing the compiler first. Now, that we want to extend the pattern matching compiler, it makes sense to add a similar script to this repository.

The other sciprts in the `tool` repository also have been copied from the Free Compiler. The original scripts have evolved since then. Further improvements are [under development](https://github.com/FreeProving/free-compiler/tree/tools/tool "Free Compiler — tools Branch"). Existing tools should be synced with the Free Compiler repository. In the future we may consider to move all scripts to their own repository and make the `tool` folder a Git submodule or something like that.

## Tasks

 - [x] Copy the `./tool/run.sh` script from the Free Compiler to this repository.
 - [x] Tweak the run script to work with `haskell-src-transformations`.
 - [x] Add documentation for the run script to the README.
 - [x] Update existing scripts to the latest version from the Free Compiler repository.
