### ISSUE TITLE
Modularize the Compiler so that `ghc-lib-parser` can be used as an alternative frontend

### ISSUE THREAD

**Issue by stu204767** [FreeProving/haskell-src-transformations#18]
## Description
Instead of having most modules inside of the same folder, the modules should be structured into submodules. This restructuring should allow using `ghc-lib-parser` can be used as an alternative to `haskell-src-exts` in the frontend.

## Motivation
As with most restructuring efforts, this should make the compiler easier to understand, maintain and develop further. Additionally, potentially switching from `haskell-src-exts` to `ghc-lib-parser` would give `haskell-src-transformations` a more stable foundation for a future, where `haskell-src-exts` might no longer be supported.

## Tasks
- [x] Shorten and split up the `Algo` module
- [x] Restructure the modules into submodules
- [x] Add a short description to every module
- [x] Prepare the addition of `ghc-lib-parser` as an alternative frontend:
  + [x] Add a new data structure for Haskell Modules, Declarations, Expressions, etc. with only the information relevant for the compiler
  + [x] Add a transformation from the `haskell-src-exts` data structure to this new data structure
  + [x] Update all modules to work with this new data structure
  + [x] Find a way to implement `haskell-src-exts` functions (especially `prettyPrint`) with this new data structure
- [ ] Develop tests to compare the Haskell language support between the old parsing approach, the new parsing approach with `haskell-src-exts` and the new parsing approach with `ghc-lib` (see specifications below)

## Tests
As our Pattern Matching Compiler does not support all features of the Haskell language, the new syntax does not include all constructs one can find in the `haskell-src-exts` or `ghc-lib` syntax. These tests should help to find the exact subset of Haskell language constructs that should be included in the new syntax.
The most important Haskell language constructs to test for are different kinds of expressions and patterns. You can find a list of all expressions ([HSE](https://hackage.haskell.org/package/haskell-src-exts-1.23.1/docs/Language-Haskell-Exts-Syntax.html#t:Exp), [`ghc-lib`](https://hackage.haskell.org/package/ghc-lib-parser-8.10.1.20200523/docs/GHC-Hs-Expr.html#t:HsExpr)) and patterns ([HSE](https://hackage.haskell.org/package/haskell-src-exts-1.23.1/docs/Language-Haskell-Exts-Syntax.html#t:Pat), [`ghc-lib`](e.haskell.org/package/ghc-lib-parser-8.10.1.20200523/docs/GHC-Hs-Pat.html#t:Pat)) supported by the parsers on the linked sites (generally, the HSE version is easier to understand).

Currently, the new syntax includes all constructs mentioned [here](https://github.com/FreeProving/haskell-src-transformations/blob/main/doc/RelevantTypes.md) (except `PAsPat`, as it caused problems) and some further constructs that are mentioned in the source code of the compiler (you can see the complete version of the new syntax [here](https://github.com/FreeProving/haskell-src-transformations/blob/issue-18/src/lib/HST/Frontend/Syntax.hs)). However, not all of these constructs are actually supported by the compiler, some expression types (specifically `Do` and `ListComp`) are specifically mentioned to be not supported yet (I have added them to the syntax anyway, because they might be supported in the future). With other expression types, specifically `NegApp`, `EnumFrom`, `EnumFromTo`, `EnumFromThen`, `EnumFromThenTo` and `ExpTypeSig` (these names are all referring to the HSE Constructor names), I'm not sure if they are actually fully supported.

In order to test this, Haskell programs containing these constructs should be developed and tested with the compiler.
Additionally, the behaviour of the compiler with the most important constructs not specifically supported by the compiler can be tested to see if they are handled correctly (the As-Pattern, for example, is not).

A continuing task would be to evaluate which of the constructs not supported currently should be added to the syntax and supported by the compiler based on importance and implementation effort.
