### ISSUE TITLE
Implement `ghc-lib` as an alternative front end

### ISSUE THREAD

**Issue by stu204767** [FreeProving/haskell-src-transformations#33]
## Description
Building on top of the new AST data structure implemented in #30, transformations from the `ghc-lib` AST data structure to our own structure and the other way around should be implemented, so that, in combination with corresponding command line option (#32), `ghc-lib` (or [`ghc-lib-parser`](https://hackage.haskell.org/package/ghc-lib-parser), to be more precise) can be used as an alternative front end.

## Motivation
The main motivation for the switch to a new AST data structure was the opportunity of using different parsers as alternative front ends. After implementing our own AST data structure and `haskell-src-exts` (the parser which we were already using previously) as one of these alternatives, the next step is to implement `ghc-lib`, which includes the parser used by the GHC itself, as the other alternative. Because of this connection to the GHC, `ghc-lib` is a more stable foundation for `haskell-src-transformations`, while the support for `haskell-src-exts` could drop at some point.

## Tasks
- [x] Take a look at the AST data structure of `ghc-lib` (a good starting point would be the type representing a Haskell module, which can be found [here](https://hackage.haskell.org/package/ghc-lib-parser-8.10.1.20200523/docs/GHC-Hs.html#t:HsModule))
  + [x] Analyze how the types in both AST data structures correspond with each other
  + [x] If necessary, make changes to our own AST data structure (for example because of information missing in the `ghc-lib` structure)
- [x] Implement the transformation from the AST data structure of `ghc-lib` to our own
- [x] Implement the missing `Eq` and `Show` instances of the `ghc-lib` type variables (the [`ghc-lib-parser-ex`](https://hackage.haskell.org/package/ghc-lib-parser-ex) module could help a bit with that)
- [x] Implement the transformation from our own AST data structure to the one of `ghc-lib`
- [x] Add command line option to be able to use the `ghc-lib` front end (see #32 and #35)
- [x] Add the `ghc-lib` part of the `processInput` function in `Main.hs` (parsing and pretty printing the module)
- [x] Let the implemented tests run with the `ghc-lib` front end as well
