### ISSUE TITLE
Non-variable pattern bindings are discarded

### ISSUE THREAD

**Issue by just95** [FreeProving/haskell-src-transformations#41]
### Description

If a module contains non-variable pattern bindings, they are discarded during the conversion from the intermediate representation to `haskell-src-exts`.

### Steps to Reproduce

Consider the following module.

```haskell
module Test where

foo = 42
(bar, baz) = (1, 2)
qux = 1337
```

#### Expected Behavior

When the pattern matching compiler is applied to the module above, the output module should be identical because `foo` and `qux` don't have to be transformed and `(bar, baz)` is skipped since it is not supported.

#### Actual Behavior

During the transformation `FromHSE`, the pattern binding `(bar, baz)` is discarded. `ToHSE` tries to interleave unsupported declarations with the transformed AST nodes. However, `ToHSE` currently [does not check](https://github.com/FreeProving/haskell-src-transformations/blob/937371112b156f22b5a8851d9906e3be68e79cbf/src/lib/HST/Frontend/ToHSE.hs#L35) whether a `PatBind` is a variable binding or not supported. `PatBind`ings in the input module are always replaced by the next transformed declaration. Thus, the binding of `(bar, baz)` is replaced by `qux = 1337`. The remaining declaration of `qux` in the input module is also copied to the output.

```haskell
module Test where

foo = 42
qux = 1337
qux = 1337
```

### Versions

 - Git commit: 1e89a4584da5cfa882706a671ae850537b91402f
 - `ghc --version`: 8.6.5
 - `cabal --version`: 2.4.1.0
 - OS: Ubuntu 20.04 LTS

### Tasks

Since it is error prone to reconstruct the original module in `ToHSE` and unsupported declarations in `let` expressions are discarded as well, we want to add additional information about the original module to the AST.

 - [x] Add a constructor `S.UnsupportedDecl` to `S.Decl`.
 - [x] Remove the `S.TypeSig` constructor from `S.Decl`.
 - [x] Add additional information to `S.Module` and `S.DataDecl` for reconstruction of original module or declaration.
   + [x] Add new type family for declaration data type and module header.
